# ----------------------------------------------------------------------
# Customizations
# ----------------------------------------------------------------------

#
# root directory of the package
#
ROOT := $(dir $(lastword $(MAKEFILE_LIST)))

# directories
SOLVER_SRCDIR_REL := src
SOLVER_OBJDIR_REL := obj
SOLVER_DEPDIR_REL := dep
SOLVER_SRCDIR := $(ROOT)/$(SOLVER_SRCDIR_REL)
SOLVER_OBJDIR := $(ROOT)/$(SOLVER_OBJDIR_REL)
SOLVER_DEPDIR := $(ROOT)/$(SOLVER_DEPDIR_REL)

# ----------------------------------------------------------------------
# Files
# ----------------------------------------------------------------------
#
SOLVER_SRCS := $(wildcard $(SOLVER_SRCDIR)/*.cc)
SOLVER_HDRS := $(wildcard $(SOLVER_SRCDIR)/*.h)
SOLVER_OBJS := $(patsubst $(SOLVER_SRCDIR)/%.cc, $(SOLVER_OBJDIR)/%.o,   $(SOLVER_SRCS))
SOLVER_DEPS := $(patsubst $(SOLVER_SRCDIR)/%.cc, $(SOLVER_DEPDIR)/%.dep, $(SOLVER_SRCS))

# ----------------------------------------------------------------------
# Target/home/lackofcheese/Research/sbt/problems/RockSample/Makefiles
# ----------------------------------------------------------------------/

$(SOLVER_OBJS) :| $(SOLVER_OBJDIR) $(SOLVER_DEPDIR)
$(SOLVER_DEPDIR) $(SOLVER_OBJDIR) :; mkdir -p $@
$(SOLVER_OBJDIR)/%.o : $(SOLVER_SRCDIR)/%.cc
	cd $(ROOT); $(CXX) $(CXXFLAGS) -MMD -MT "\$$(SOLVER_OBJDIR)/$*.o" \
		-c $(SOLVER_SRCDIR_REL)/$*.cc -o $(SOLVER_OBJDIR_REL)/$*.o
	@mv $(SOLVER_OBJDIR)/$*.d $(SOLVER_DEPDIR)/$*.dep
