MODULE_NAME = search

ifdef HAS_ROOT_MAKEFILE

CHILD_FOLDERS := steppers action-choosers

include .make/template.mk
include .make/build.mk   

else
ROOT = ../../..
include $(ROOT)/.make/redirect.mk
endif
