#!/bin/bash


for (( i = 0 ; i < 30 ; i=i+5 ))
do
	echo Generate Epoch starting at $i to $j
	j=$(( $i+5 ))
	#./runAnEpoch $i $j ./exp2 map-52X51-v3 changes-v3-2 param-v21 200 100 &
	./runAnEpoch $i $j ./exp3 map-52X51-v3 changes-v3-2 param-v22b 200 10 &
	sleep 1
done
