#!/bin/bash

for (( i = 0 ; i < 30 ; i=i+30 ))
do
	echo Generate Epoch starting at $i to $j
	j=$(( $i+30 ))
	./runAnEpoch $i $j ./exp3 map-52X51-v3 changes-v3-2 param-v20 200 30 &
	sleep 1
done

for (( i = 0 ; i < 30 ; i=i+15 ))
do
	echo Generate Epoch starting at $i to $j
	j=$(( $i+15 ))
	./runAnEpoch $i $j ./exp3 map-52X51-v3 changes-v3-2 param-v21 200 30 &
	./runAnEpoch $i $j ./exp3 map-52X51-v3 changes-v3-2 param-v22 200 30 &
	sleep 1
done
